"""
Django settings for Joffgram project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&*pgk1u)!70wk-s#5blmv$68j6hr7p*31dfa6h7np5xhp=_)r3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

AUTH_USER_MODEL = 'account.Account'
# Application definition

INSTALLED_APPS = [
    # django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # our apps
    'base.apps.BaseConfig',
    'account.apps.AccountConfig',
    'follower.apps.FollowerConfig',
    'post.apps.PostConfig',
    'private_chat.apps.PrivateChatConfig',
    'notification.apps.NotificationConfig',
    'story.apps.StoryConfig',

    # third party
    'rest_framework',
    'corsheaders',
    'channels'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    
    'corsheaders.middleware.CorsMiddleware',
    
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Joffgram.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Joffgram.wsgi.application'
ASGI_APPLICATION = 'Joffgram.routing.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DB_NAME = '*YOUR POSTGRES DATABASE NAME*'
DB_USER = '* YOUR POSTGRES DATABASE USER NAME *'
DB_PASSWORD = '*YOUR POSTGRES DB USER PASSWORD*'
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'media'
]

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATIC_ROOT = BASE_DIR / 'static_cdn'
MEDIA_ROOT = BASE_DIR / 'media_cdn'

TEMP = BASE_DIR / 'media_cdn/temp'


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ORIGIN_ALLOW_ALL = True
CORS_URLS_REGEX = r"^/api/.*$" 


DEFAULT_RENDERER_CLASSES = [
    'rest_framework.renderers.JSONRenderer',
]

DEFAULT_AUTHENTICATION_CLASSES = [
    'rest_framework.authentication.SessionAuthentication'
]



if DEBUG:
    DEFAULT_RENDERER_CLASSES += [
        'rest_framework.renderers.BrowsableAPIRenderer'
    ]
        
    DEFAULT_AUTHENTICATION_CLASSES += [
        'Joffgram.rest_api.dev.DevAuthentication'
    ]



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': DEFAULT_AUTHENTICATION_CLASSES,

    'DEFAULT_RENDERER_CLASSES': DEFAULT_RENDERER_CLASSES
}

LOGIN_URL = '/login'

STORIES_ROUTE = BASE_DIR / 'media_cdn/stories'
POSTS_ROUTE = BASE_DIR / 'media_cdn/posts'
PROFILE_IMAGES_ROUTE = BASE_DIR / 'media_cdn/profile_images'
PRIVATE_CHAT_IMAGES_ROUTE = BASE_DIR / 'media_cdn/messages'
PRIVATE_CHAT_FILES_ROUTE = BASE_DIR / 'media_cdn/messages'

DATA_UPLOAD_MAX_MEMORY_SIZE = 10_485_760 # 10 * 1024 * 1024 => 10 MB


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com' # YOU CAN CHANGE THIS AS YOU WANT
EMAIL_PORT  = 587
EMAIL_USE_TLS = True # DEPENDS ON WHICH ONE YOU USE 
EMAIL_HOST_USER = '*EMAIL ADDRESS YOU WANT TO SEND EMAILS FROM*'
EMAIL_HOST_PASSWORD = '*PASSWORD TO THIS ADDRESS*'

MAIN_DOMAIN = 'http://127.0.0.1:8000'


