# Generated by Django 4.0.4 on 2022-04-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_delete_savedposts'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='saved_posts',
            field=models.ManyToManyField(to='post.post'),
        ),
    ]
