# Generated by Django 4.0.4 on 2022-05-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_delete_savedposts'),
        ('account', '0002_account_saved_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='saved_posts',
            field=models.ManyToManyField(blank=True, to='post.post'),
        ),
    ]
