# Generated by Django 4.0.4 on 2022-05-04 18:01

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_delete_savedposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=post.models.get_post_image_filepath),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=post.models.get_post_image_filepath),
        ),
    ]
