# Generated by Django 4.0.4 on 2022-05-14 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_post_video_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('comment_on_post', 'comment_on_post'), ('like_on_post', 'like_on_post'), ('follow_request_sent', 'follow_request_sent'), ('new_follower', 'new_follower'), ('response_on_comment', 'response_on_comment')], max_length=50)),
                ('seen', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_notifications', to='post.postcomment')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_received_notifications', to=settings.AUTH_USER_MODEL)),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_notifications', to='post.postcommentreply')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
