# Generated by Django 4.0.4 on 2022-05-14 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='reply',
        ),
        migrations.AddField(
            model_name='notification',
            name='comment_body',
            field=models.CharField(blank=True, max_length=2200, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='reply_body',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
