# Generated by Django 4.0.4 on 2022-05-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_remove_notification_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='post_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
