# Generated by Django 4.0.4 on 2022-05-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='story_comment_body',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('comment_on_post', 'comment_on_post'), ('comment_on_story', 'comment_on_story'), ('like_on_post', 'like_on_post'), ('follow_request_sent', 'follow_request_sent'), ('new_follower', 'new_follower'), ('response_on_comment', 'response_on_comment'), ('follow_request_accepted', 'follow_request_accepted')], max_length=50),
        ),
    ]
