# Generated by Django 4.0.4 on 2022-05-19 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 20, 18, 40, 20, 790316)),
        ),
    ]
