# Generated by Django 4.0.4 on 2022-05-20 18:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0002_alter_story_expiry_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={},
        ),
        migrations.AlterField(
            model_name='story',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 20, 1, 40, 579991)),
        ),
        migrations.CreateModel(
            name='StoryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
