# Generated by Django 4.0.4 on 2022-05-20 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_alter_story_options_alter_story_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 20, 13, 47, 706761)),
        ),
    ]
