# Generated by Django 4.0.4 on 2022-05-20 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_alter_story_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 20, 25, 10, 125823)),
        ),
        migrations.DeleteModel(
            name='StoryComment',
        ),
    ]
