# Generated by Django 4.0.4 on 2022-05-04 18:01

from django.db import migrations, models
import private_chat.models


class Migration(migrations.Migration):

    dependencies = [
        ('private_chat', '0002_privatechatmessage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechatmessage',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=private_chat.models.get_message_image_filepath),
        ),
    ]
