# Generated by Django 4.0.4 on 2022-05-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_chat', '0004_remove_privatechatmessage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechatmessage',
            name='body',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
