# Generated by Django 4.0.4 on 2022-05-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_chat', '0005_alter_privatechatmessage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechatmessage',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
