# Generated by Django 4.0.4 on 2022-05-13 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('private_chat', '0006_privatechatmessage_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechat',
            name='currently_connected_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
